import type { Metadata } from "next";
import "./globals.css";
import { Topnav } from "@/components/nav/top-nav";
import { SuitFont } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${SuitFont.className} antialiased`}>
        <Topnav />
        {children}
      </body>
    </html>
  );
}
